# Generated by Django 4.1.2 on 2023-04-16 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("mobile_number", models.CharField(max_length=15)),
                ("otp", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="activityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=None, max_length=50)),
                ("session", models.CharField(max_length=50)),
                ("submission_id", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
