# Generated by Django 4.1.2 on 2023-04-16 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webauthn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FIDO_Authenticator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("properties", jsonfield.fields.JSONField(null=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("key_type", models.CharField(default="TOTP", max_length=25)),
                ("enabled", models.BooleanField(default=True)),
                ("expires", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "last_used",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "owned_by_enterprise",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
