# Generated by Django 4.1.2 on 2023-03-05 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AI_Coursework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Submission_Date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Group", "Group")],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("module", models.CharField(default="AI", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_convenor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDL_Coursework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Submission_Date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Group", "Group")],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("module", models.CharField(default="HDL", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_convenor2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PE_Coursework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Submission_Date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Group", "Group")],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("module", models.CharField(default="PE", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_convenor3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Label"
                    ),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        max_length=30,
                        region=None,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Extension"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PE_Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docfile_individual",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="Power_Electronic_Folder_Individual",
                    ),
                ),
                (
                    "docfile_group",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="Power_Electronic_Folder_Group",
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "submission_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "similarity",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "leader_approval",
                    models.CharField(default="Not Required", max_length=50),
                ),
                ("lecturer_signature", models.BooleanField(default=False)),
                (
                    "signature_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("signed_by", models.CharField(default="None", max_length=50)),
                (
                    "access_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Coursework",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.pe_coursework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="leader_approval_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[("AI", "AI"), ("PE", "PE"), ("HDL", "HDL")],
                        default=None,
                        max_length=10,
                    ),
                ),
                (
                    "submission_title",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "access_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("pending_approval", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDL_Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docfile_individual",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="HDL_Folder_Individual",
                    ),
                ),
                (
                    "docfile_group",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="HDL_Folder_Group",
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "submission_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "similarity",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "leader_approval",
                    models.CharField(default="Not Required", max_length=50),
                ),
                ("lecturer_signature", models.BooleanField(default=False)),
                (
                    "signature_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("signed_by", models.CharField(default="None", max_length=50)),
                (
                    "access_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Coursework",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.hdl_coursework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AI_Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "docfile_individual",
                    models.FileField(blank=True, default=None, null=True, upload_to=""),
                ),
                (
                    "docfile_group",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="AI_Folder_Group"
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "submission_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "similarity",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=4, null=True
                    ),
                ),
                (
                    "leader_approval",
                    models.CharField(default="Not Required", max_length=50),
                ),
                ("lecturer_signature", models.BooleanField(default=False)),
                (
                    "signature_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("signed_by", models.CharField(default="None", max_length=50)),
                (
                    "access_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "Coursework",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.ai_coursework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Additional_User_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Lecturer", "Lecturer"), ("Student", "Student")],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "module_convenor",
                    models.CharField(
                        blank=True,
                        choices=[("AI", "AI"), ("PE", "PE"), ("HDL", "HDL")],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        max_length=30,
                        region=None,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Extension"
                    ),
                ),
                (
                    "default_authentication_method",
                    models.CharField(
                        choices=[
                            ("Password", "Password"),
                            ("OTP", "OTP"),
                            ("FIDO", "FIDO"),
                        ],
                        default="FIDO",
                        max_length=10,
                    ),
                ),
                (
                    "multi_factor_authentication_method",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Password", "Password"),
                            ("OTP", "OTP"),
                            ("FIDO", "FIDO"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "digital_signature",
                    models.CharField(default="Not Required", max_length=50),
                ),
                (
                    "digital_signature_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
