# Generated by Django 4.1.2 on 2023-03-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai_document",
            name="a",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
