# Generated by Django 4.1.2 on 2023-03-05 05:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_ai_document_docfile_individual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai_document",
            name="a",
        ),
        migrations.AlterField(
            model_name="ai_document",
            name="docfile_group",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
        migrations.AlterField(
            model_name="hdl_document",
            name="docfile_group",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
        migrations.AlterField(
            model_name="hdl_document",
            name="docfile_individual",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
        migrations.AlterField(
            model_name="pe_document",
            name="docfile_group",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
        migrations.AlterField(
            model_name="pe_document",
            name="docfile_individual",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
    ]
