# Generated by Django 4.1.2 on 2023-03-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_ai_document_a_alter_ai_document_docfile_group_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="choices",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="PhoneNumber",
        ),
    ]
