# Generated by Django 4.1.2 on 2023-03-10 05:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_ai_document_docfile_individual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ai_document",
            name="docfile_group",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                upload_to=home.models.rename_uploaded_file,
            ),
        ),
    ]
