# Generated by Django 4.1.2 on 2023-03-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_ai_document_coursework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdl_document",
            name="Coursework",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hdl_coursework",
                to="home.hdl_coursework",
            ),
        ),
        migrations.AlterField(
            model_name="pe_document",
            name="Coursework",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pe_coursework",
                to="home.pe_coursework",
            ),
        ),
    ]
